### ISSUE TITLE
default value to parameter ?

### ISSUE THREAD

**Issue by originalankur** [pavanmishra/cup#1]
def GET(self, name):
    if not name:
      name = 'World'
    return 'Hello, ' + name + '!'

wouldn't this work ?

 def GET(self, name='World'):
    return 'Hello, ' + name + '!'

**Comment by pavanmishra** [comment]
Not only the example is taken from web.py but also behavior. It does not work for either of them.

**Comment by originalankur** [comment]
okay. Never used web.py. Doesn't it break python itself by enforcing that default parameter values cannot be used ?. Anyways closing the issue. Thanks for letting me know.

**Comment by pavanmishra** [comment]
Interesting observation, I can guess why web.py works that way and so does cup. Anyways, respecting that behavior will definitely yield for more pythonic interfaces. Thanks for the input and food for thought.
