### ISSUE TITLE
Request for ownship transfer for cup in pypi

### ISSUE THREAD

**Issue by mythmgn** [pavanmishra/cup#2]
Hi pavan,

Seems cup on pypi.org has not been maintained since 2014. Wondering if there's a chance our project (https://github.com/baidu/CUP) can use the name "cup" in pypi per PEP 541. 

If you see the issue, plz contact me through my email addr. (already sent an email to you several days ago)

Thanks very much.

---Gallon

**Comment by mythmgn** [comment]
@pavanmishra  Hi Pavan,  plz have a look if you have any time.  thank u very much.

**Comment by pavanmishra** [comment]
Hey,

No problem, please let me know what I need to do, so that I can do it
quickly or else will figure it out.

Thanks,
Pavan

**Comment by mythmgn** [comment]
@pavanmishra 

hi pavan, 

https://pypi.org/account/login/

Login with your pypy account. And see the left panel, there's a item called " Your projects".

You can add my pypi account to cup admin list.  That would be all you may do.

Account:      mythmgn   

Thank you again.

**Comment by pavanmishra** [comment]
Hi Guannan Ma,

I have added you as an owner of the account. Hope now you can move ahead
and do the needful.

Cheers,
Pavan

**Comment by mythmgn** [comment]
@pavanmishra  

Auth confirmed.  

Thank you so much for the help.  Long live the spirit of the opensource.
